// See: //www.gatsbyjs.com/docs/gatsby-config/

const path = require(`path`);


// ------------------------------------------------------------------
// Metadata for Space Robotics #2 at IEEE SMC-IT/SCC 2025
spacerobotics2025metadata = {
  organizers: [
    {
      challenge: false,
      imageId: "ignacioGLopezFrancos",
      name: "Ignacio G. López-Francos",
      oc: true,
      lo: true,
      organization: "NASA Ames",
      sab: false,
      site: "https://www.linkedin.com/in/ilopezfrancos/",
    },
    {
      challenge: false,
      imageId: "brianColtin",
      name: "Brian Coltins",
      oc: true,
      lo: true,
      organization: "NASA Ames",
      sab: false,
      site: "https://brian.coltin.org/",
    },
    {
      challenge: true,
      imageId: "alexSowell",
      name: "Alex Sowell",
      oc: true,
      lo: false,
      organization: "NASA JSC",
      sab: false,
      site: "https://www.linkedin.com/in/samuel-alex-sowell-07695671/",
    },
    {
      challenge: false,
      imageId: "robRoyce",
      name: "Rob Royce",
      oc: true,
      lo: false,
      organization: "NASA JPL",
      sab: false,
      site: "https://www.linkedin.com/in/robroyce/",
    },
    {
      challenge: false,
      imageId: "marcelKaufmann",
      name: "Marcel Kaufmann",
      oc: true,
      lo: false,
      organization: "NASA JPL",
      sab: false,
      site: "https://www.linkedin.com/in/kaufmann-space",
    },
    {
      challenge: false,
      imageId: "kuldeepRambhai",
      name: "Kuldeep Rambhai",
      oc: true,
      lo: false,
      organization: "Redwire",
      sab: false,
      site: "https://www.linkedin.com/in/kuldeepbarad/",
    },
    {
      challenge: false,
      imageId: "ricardMarsal",
      name: "Ricard Marsal I Castan",
      oc: true,
      lo: false,
      organization: "University of Luxembourg",
      sab: false,
      site: "https://www.linkedin.com/in/ricard-marsal-44ba63155/",
    },
    {
      challenge: true,
      imageId: "maggieWang",
      name: "Maggie Wang",
      oc: true,
      lo: false,
      organization: "Stanford University",
      sab: false,
      site: "https://www.linkedin.com/in/maggie-wang/",
    },

    // Scientific Committee
    {
      challenge: false,
      imageId: "edwardBalaban",
      name: "Edward Balaban",
      oc: false,
      lo: false,
      organization: "NASA ARC",
      sab: true,
      site:"",
    },
    {
      challenge: false,
      imageId: "jenBlank",
      name: "Jen Blank",
      oc: false,
      lo: false,
      organization: "Blue Marble Space Institute of Science",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "giuseppeCataldo",
      name: "Giuseppe Cataldo",
      oc: false,
      lo: false,
      organization: "NASA GSFC",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "jeanPierreDeLaCroix",
      name: "Jean-Pierre de la Croix",
      oc: false,
      lo: false,
      organization: "NASA JPL",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "animeshGarg",
      name: "Animesh Garg",
      oc: false,
      lo: false,
      organization: "Georgia Tech, NVIDIA, Apptronik",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "keerthanaGopalakrishnan",
      name: "Keerthana Gopalakrishnan",
      oc: false,
      lo: false,
      organization: "Google DeepMind",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "jenHeldmann",
      name: "Jen Heldmann",
      oc: false,
      lo: false,
      organization: "NASA ARC",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "pyojinKim",
      name: "Pyojin Kim",
      oc: false,
      lo: false,
      organization: "Gwangju Institute of Science and Technology (GIST)",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "jonathanKnowles",
      name: "Jonathan Knowles",
      oc: false,
      lo: false,
      organization: "Former Autodesk, Apple, Adobe",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "robertoLampariello",
      name: "Roberto Lampariello",
      oc: false,
      lo: false,
      organization: "DLR (German Aerospace Center)",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "alisonLowndes",
      name: "Alison Lowndes",
      oc: false,
      lo: false,
      organization: "NVIDIA",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "luisMerino",
      name: "Luis Merino",
      oc: false,
      lo: false,
      organization: "Universidad Pablo de Olavide",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "hiroOno",
      name: "Hiro Ono",
      oc: false,
      lo: false,
      organization: "NASA JPL",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "katherineScott",
      name: "Katherine Scott",
      oc: false,
      lo: false,
      organization: "Intrinsic, Open Robotics",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "luisSentis",
      name: "Luis Sentis",
      oc: false,
      lo: false,
      organization: "University of Texas at Austin, Apptronik",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "treySmith",
      name: "Trey Smith",
      oc: false,
      lo: false,
      organization: "NASA ARC",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "johnathanStock",
      name: "Johnathan Stock",
      oc: false,
      lo: false,
      organization: "NASA ARC",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "kentaroUno",
      name: "Kentaro Uno",
      oc: false,
      lo: false,
      organization: "Tohoku University",
      sab: true,
      site: "",
    },
    {
      challenge: false,
      imageId: "rodrigoVentura",
      name: "Rodrigo Ventura",
      oc: false,
      lo: false,
      organization: "Instituto Superior Técnico (IST), University of Lisbon",
      sab: true,
      site: "",
    },
  ],
};

// ------------------------------------------------------------------
// Sitewide metadata used to generate pages.
module.exports = {
  siteMetadata: {
    spacerobotics2025: spacerobotics2025metadata,
  },
  plugins: [
    `gatsby-plugin-typescript`,
    `gatsby-plugin-sass`,
    `gatsby-plugin-antd`,
    `gatsby-plugin-react-helmet`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-emotion`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: path.join(__dirname, `static`, `images`),
      },
    },
    {
      resolve: `gatsby-plugin-google-gtag`,
      options: {
        trackingIds: ["UA-120916510-7"],
      },
    },
  ],
};
