// See: //www.gatsbyjs.com/docs/gatsby-config/

const path = require(`path`);


// ------------------------------------------------------------------
// Metadata for Space Robotics #2 at IEEE SMC-IT/SCC 2025
spacerobotics2025metadata = {
  organizers: [
    {
      challenge: false,
      imageId: "ignacioGLopezFrancos",
      name: "Ignacio G. López-Francos",
      oc: true,
      lo: true,
      organization: "Nasa Ames",
      sab: false,
      site: "",
    },
    {
      challenge: false,
      imageId: "brianColtin",
      name: "Brian Coltins",
      oc: true,
      lo: true,
      organization: "Nasa Ames",
      sab: false,
      site: "",
    },
    {
      challenge: true,
      imageId: "alexSowell",
      name: "Alex Sowell",
      oc: true,
      lo: false,
      organization: "Nasa JSC",
      sab: false,
      site: "",
    },
    {
      challenge: false,
      imageId: "robRoyce",
      name: "Rob Royce",
      oc: true,
      lo: false,
      organization: "Nasa JPL",
      sab: false,
      site: "",
    },
    {
      challenge: false,
      imageId: "marcelKaufmann",
      name: "Marcel Kaufmann",
      oc: true,
      lo: false,
      organization: "Nasa JPL",
      sab: false,
      site: "",
    },
    {
      challenge: false,
      imageId: "kuldeepRambhai",
      name: "Kuldeep Rambhai",
      oc: true,
      lo: false,
      organization: "Redwire",
      sab: false,
      site: "",
    },
    {
      challenge: false,
      imageId: "ricardMarsal",
      name: "Ricard Marsal I Castan",
      oc: true,
      lo: false,
      organization: "University of Luxembourg",
      sab: false,
      site: "",
    },
    {
      challenge: true,
      imageId: "maggieWang",
      name: "Maggie Wang",
      oc: true,
      lo: false,
      organization: "Stanford",
      sab: false,
      site: "",
    },
  ],
};
// ------------------------------------------------------------------
cvpr2025metadata = {
  organizers: [
    {
      challenge: false,
      imageId: "adeFamoti",
      name: "Ade Famoti",
      oc: false,
      lo: false,
      organization: "Microsoft",
      sab: true,
      site: "https://www.microsoft.com/en-us/research/people/adfamoti/",
    },
    {
      challenge: false,
      imageId: "andreyKolobov",
      name: "Andrey Kolobov",
      oc: false,
      lo: false,
      organization: "Microsoft",
      sab: true,
      site: "https://www.microsoft.com/en-us/research/people/akolobov/",
    },
    {
      challenge: true,
      imageId: "angel",
      name: "Angel X. Chang",
      oc: true,
      lo: false,
      organization: "SFU",
      sab: true,
      site: "https://angelxuanchang.github.io/",
    },
    {
      challenge: false,
      imageId: "anthony",
      name: "Anthony Francis",
      oc: true,
      lo: true,
      organization: "Logical Robotics",
      sab: false,
      site: "https://logicalrobotics.com/",
    },
    {
      challenge: true,
      imageId: "baoxiongJia",
      name: "Baoxiong Jia",
      oc: false,
      lo: false,
      organization: "BIGAI",
      sab: false,
      site: "https://scholar.google.com/citations?user=qIBUK6sAAAAJ&hl=en",
    },        
    {
      challenge: true,
      imageId: "changan",
      name: "Changan Chen",
      oc: true,
      lo: false,
      organization: "Stanford",
      sab: false,
      site: "https://changan.io/",
    },
    {
      challenge: false,
      imageId: "chengshu",
      name: "Chengshu Li",
      oc: true,
      lo: false,
      organization: "Stanford",
      sab: false,
      site: "https://www.chengshuli.me/",
    },
    {
      challenge: true,
      imageId: "chris",
      name: "Chris Paxton",
      oc: true,
      lo: false,
      organization: "Meta AI",
      sab: false,
      site: "https://cpaxton.github.io/about/",
    },
    {
      challenge: true,
      imageId: "chuang",
      name: "Chuang Gan",
      oc: false,
      lo: false,
      organization: "IBM, MIT",
      sab: false,
      site: "https://people.csail.mit.edu/ganchuang/",
    },
    {
      challenge: false,
      imageId: "claudia",
      name: "Claudia Pérez D\u2019Arpino",
      oc: true,
      lo: true,
      organization: "NVIDIA",
      sab: false,
      site: "https://ai.stanford.edu/~cdarpino/",
    },
    {
      challenge: false,
      imageId: "davidH",
      name: "David Hall",
      oc: true,
      lo: false,
      organization: "CSIRO",
      sab: false,
      site: "https://sites.google.com/view/davidhallcv/home",
    },
    {
      challenge: false,
      imageId: "devon",
      name: "Devon Hjelm",
      oc: true,
      lo: false,
      organization: "Apple",
      sab: false,
      site: "https://rdevon.github.io/",
    },
    {
      challenge: true,
      imageId: "dhruv",
      name: "Dhruv Batra",
      oc: false,
      lo: false,
      organization: "Yutori",
      sab: true,
      site: "https://dhruvbatra.com/",
    },
    {
      challenge: false,
      imageId: "german",
      name: "German Ros",
      oc: true,
      lo: false,
      organization: "NVIDIA",
      sab: false,
      site: "https://germanros.net/",
    },
    {
      challenge: true,
      imageId: "jiangyongHuang",
      name: "Jiangyong Huang",
      oc: false,
      lo: false,
      organization: "Peking U",
      sab: false,
      site: "https://huangjy-pku.github.io/",
    },
    {
      challenge: false,
      imageId: "joanne",
      name: "Joanne Truong",
      oc: true,
      lo: false,
      organization: "GaTech",
      sab: true,
      site: "https://www.joannetruong.com/",
    },
    {
      challenge: false,
      imageId: "lamberto",
      name: "Lamberto Ballan",
      oc: true,
      lo: false,
      organization: "U Padova",
      sab: false,
      site: "http://www.lambertoballan.net/",
    },
    {
      challenge: true,
      imageId: "luca",
      name: "Luca Weihs",
      oc: true,
      lo: true,
      organization: "Vercept",
      sab: false,
      site: "https://lucaweihs.github.io/",
    },
    {
      challenge: true,
      imageId: "manolis",
      name: "Manolis Savva",
      oc: false,
      lo: false,
      organization: "SFU",
      sab: true,
      site: "https://msavva.github.io/",
    },
    {
      challenge: false,
      imageId: "mike",
      name: "Mike Roberts",
      oc: true,
      lo: false,
      organization: "Intel",
      sab: false,
      site: "https://mikeroberts3000.github.io/",
    },
    {
      challenge: true,
      imageId: "naoki",
      name: "Naoki Yokoyama",
      oc: true,
      lo: false,
      organization: "GaTech",
      sab: false,
      site: "http://naoki.io/",
    },
    {
      challenge: true,
      imageId: "oleksandr",
      name: "Oleksandr Maksymets",
      oc: true,
      lo: false,
      organization: "Meta AI",
      sab: false,
      site: "https://research.facebook.com/people/maksymets-oleksandr/",
    },
    {
      challenge: true,
      imageId: "ram",
      name: "Ram Ramrakhya",
      oc: true,
      lo: false,
      organization: "Gatech",
      sab: false,
      site: "https://ram81.github.io/",
    },
    {
      challenge: false,
      imageId: "ranGong",
      name: "Ran Gong",
      oc: true,
      lo: false,
      organization: "UCLA",
      sab: false,
      site: "https://nikepupu.github.io/",
    },
    {
      challenge: true,
      imageId: "richardHeBai",
      name: "Richard He Bai",
      oc: false,
      lo: false,
      organization: "Apple",
      sab: false,
      site: "https://richardbaihe.github.io/",
    },
    {
      challenge: false,
      imageId: "roberto",
      name: "Roberto Mart\u00edn-Mart\u00edn",
      oc: false,
      lo: false,
      organization: "Stanford",
      sab: true,
      site: "https://robertomartinmartin.com/",
    },
    {
      challenge: true,
      imageId: "siyuanHuang",
      name: "Siyuan Huang",
      oc: false,
      lo: false,
      organization: "BIGAI",
      sab: false,
      site: "https://siyuanhuang.com/",
    },
    {
      challenge: false,
      imageId: "sorean",
      name: "S\u00f6ren Pirk",
      oc: false,
      lo: false,
      organization: "Kiel University",
      sab: true,
      site: "https://www.pirk.io",
    },
    {
      challenge: true,
      imageId: "xiaofeng",
      name: "Xiaofeng Gao",
      oc: false,
      lo: false,
      organization: "Amazon",
      sab: false,
      site: "https://xfgao.github.io/",
    },
    {
      challenge: true,
      imageId: "yonatan",
      name: "Yonatan Bisk",
      oc: true,
      lo: false,
      organization: "CMU",
      sab: false,
      site: "https://yonatanbisk.com/",
    },
    {
      challenge: false,
      imageId: "rachith",
      name: "Rachith Prakash",
      oc: true,
      lo: false,
      organization: "Intel",
      sab: false,
      site: "https://rachithp.github.io/",
    },
    {
      challenge: false,
      imageId: "vivan",
      name: "Vivan Amin",
      oc: true,
      lo: false,
      organization: "Microsoft",
      sab: false,
      site: "https://www.microsoft.com/en-us/research/people/aminvivan/",
    },
    {
      challenge: false,
      imageId: "jiaolong",
      name: "Jiaolong Yang",
      oc: true,
      lo: false,
      organization: "Microsoft",
      sab: false,
      site: "https://jlyang.org/",
    },
    {
      challenge: false,
      imageId: "minyoung",
      name: "Minyoung Hwang",
      oc: true,
      lo: false,
      organization: "MIT",
      sab: false,
      site: "https://minyoung1005.github.io/",
    },
    {
      challenge: false,
      imageId: "lars",
      name: "Lars Johannsmeier",
      oc: true,
      lo: false,
      organization: "NVIDIA",
      sab: false,
      site: "https://research.nvidia.com/person/lars-johannsmeier",
    },
    {
      challenge: false,
      imageId: "cem",
      name: "Cem Gokmen",
      oc: true,
      lo: false,
      organization: "Stanford",
      sab: false,
      site: "https://www.cemgokmen.com/",
    },
  ]
};



// ------------------------------------------------------------------
// Sitewide metadata used to generate pages.
module.exports = {
  siteMetadata: {
    spacerobotics2025: spacerobotics2025metadata,
  },
  plugins: [
    `gatsby-plugin-typescript`,
    `gatsby-plugin-sass`,
    `gatsby-plugin-antd`,
    `gatsby-plugin-react-helmet`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-emotion`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: path.join(__dirname, `static`, `images`),
      },
    },
    {
      resolve: `gatsby-plugin-google-gtag`,
      options: {
        trackingIds: ["UA-120916510-7"],
      },
    },
  ],
};
